title: Resk-status
languageCode: fr
params:
  copyrightHolder: Resk-U SÃ rl
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>example</a> systems operations.<br />Follow
    us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/example'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  groups:
    - Serveur Nextcloud
    - Serveur Dolibarr
    - Robot Resk-U
  logo: /images/clearstatus.svg
  meta_description: >-
    This status page provides updated information about our systems normal
    operation, incidents that may happen and their resolution.
  shortDateFormat: 'Jan 2 15:04'
  systems:
    - description: Our company public facing website
      link: 'https://www.example.com/'
      name: Website
    - description: Our company customer support site
      link: 'https://support.example.com/'
      name: Helpdesk
  timezoneString: Europe/Zurich
